version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.5
    working_directory: /go/src/github.com/mobingi/mobingi
    steps:
    - checkout
    - run:
        name: build
        shell: /bin/bash
        command: |
          GO111MODULE=on go test -v ./... -count=1
